version: "3.8"
services:
  backend:
    image: "rubenlangeweg/ravel-backend-01:7.12.2021.8.46.49"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
