package com.ravel.backend.appAuth.enumeration;

public enum RoleName {
	ORGANIZATION_ADMIN,
	ORGANIZATION_OWNER,
	ORGANIZATION_USER,
	ORGANIZATION_GUEST,
	ROOM_PRESENTER,
	ROOM_GUEST,
	ROOM_MODERATOR,
	ROOM_CAMERA,
	ROOM_DEVELOPER,
	SPACE_PRESENTER,
	SPACE_GUEST,
	SPACE_MODERATOR,
	SPACE_CAMERA,
	SPACE_DEVELOPER,
	PRESENTER,
	MODERATOR,
	DEVELOPER,
	USER,
	GUEST,
	VISITOR,
}
